name: github pages
on: ["push", "workflow_dispatch"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build
        run: hugo --minify -F
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          repository: mametaro99/mametaro99.github.io
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/posts
          user_name: 'mametaro99'
          user_email: 'bearsmichimato99@gmail.com'
          commit_message: ${{ github.event.head_commit.message }}
          target_branch: gh-pages